name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # Specify the distribution
        java-version: '17'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./vdt2024/gradlew
      
    - name: Build with Gradle
      run: ./vdt2024/gradlew build
    
    - name: Run unit tests
      run: ./gradlew test
